services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: web-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: admin-app
    restart: always
    ports:
      - "3001:3000" # Maps local port 3001 to container port 3000
    env_file:
      - ./apps/admin/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: apps/workers/Dockerfile
    # When using multiple replicas, remove fixed container_name, or Docker compose will throw an error since multiple containers cannot have the same name.
    # container_name: background-worker
    restart: always
    env_file:
      - ./apps/workers/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 3

  redis:
    build:
      context: ./infra/redis
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    build:
      context: ./infra/rabbitmq
    container_name: rabbitmq-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

