# # RabbitMQ Configuration File

# # Network and Protocol
# listeners.ssl.default = 5671
listeners.tcp.default = 5672


# # Management plugin
management.tcp.port = 15672

# # Clustering
# cluster_partition_handling = autoheal

# # Memory
# vm_memory_high_watermark.relative = 0.6

# # Disk free limit
disk_free_limit.absolute = 50MB

# # Channel timeout
# channel_max = 2048
# connection_max = unlimited

# # Message delivery
# max_message_size = 134217728

# # Queue master location
# queue_master_locator = min-masters

# # Performance tuning
# channel_operation_timeout = 15000
# heartbeat = 60
# frame_max = 131072
